### ISSUE TITLE
Build spirv-cross in parallel

### ISSUE THREAD

**Issue by The-Minecraft-Scientist** [SnowflakePowered/spirv-cross2-rs#5]
Building `spirv-cross2` in parallel when possible would save significant amounts of initial build time for users of this crate. The related `glslang` crate would also benefit greatly from this

**Comment by chyyran** [comment]
Fixed in https://github.com/SnowflakePowered/spirv-cross2-rs/pull/6

Fixed for `glslang` in https://github.com/SnowflakePowered/glslang-rs/pull/7
