### ISSUE TITLE
`Compiler::set_compiler_options` not marked public

### ISSUE THREAD

**Issue by The-Minecraft-Scientist** [SnowflakePowered/spirv-cross2-rs#7]
Looks like a typo :)

**Comment by chyyran** [comment]
Ah, `set_compiler_options` is private for safety reasons!

You want [`Compiler<T: CompilableTarget>::compile`](https://docs.rs/spirv-cross2/latest/spirv_cross2/struct.Compiler.html#method.compile), which takes a ref to the options struct type for `T`. 

note: `compile` is only available for targets that can be compiled, so the `None` target doesn't have this.

**Comment by The-Minecraft-Scientist** [comment]
Oh lol, I was trying to figure out where to actually set the options but I forgot to look at the compile function itself. I apparently can't read

Thanks :)
